/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberito.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author renat
 */
public class Calculadora extends javax.swing.JInternalFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jCoordenadaXInicial = new javax.swing.JTextField();
        jCoordenadaYInicial = new javax.swing.JTextField();
        jCoordenadaYFinal = new javax.swing.JTextField();
        jCoordenadaXFinal = new javax.swing.JTextField();
        jDistancia = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Coordenada X :");

        jLabel2.setText("Coordenada Y :");

        jLabel3.setText("Distancia en metros:");

        jLabel4.setText("Coordenada X :");

        jLabel5.setText("Coordenada Y :");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jCoordenadaXInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoordenadaXInicialActionPerformed(evt);
            }
        });
        jCoordenadaXInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCoordenadaXInicialKeyTyped(evt);
            }
        });

        jCoordenadaYInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoordenadaYInicialActionPerformed(evt);
            }
        });
        jCoordenadaYInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCoordenadaYInicialKeyTyped(evt);
            }
        });

        jCoordenadaYFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCoordenadaYFinalKeyTyped(evt);
            }
        });

        jCoordenadaXFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCoordenadaXFinalKeyTyped(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Calculadora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCoordenadaXInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCoordenadaYInicial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jCoordenadaXFinal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCoordenadaYFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(btnLimpiar)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jCoordenadaXInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCoordenadaXFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jCoordenadaYInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCoordenadaYFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnCalcular)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCoordenadaXInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoordenadaXInicialActionPerformed
        
    }//GEN-LAST:event_jCoordenadaXInicialActionPerformed

    private void jCoordenadaYInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoordenadaYInicialActionPerformed
        
    }//GEN-LAST:event_jCoordenadaYInicialActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double Calculo = 0;
        try {
            int CoorXIni = Integer.parseInt(jCoordenadaXInicial.getText());
            int CoorXFin = Integer.parseInt(jCoordenadaXFinal.getText());
            int CoorYIni = Integer.parseInt(jCoordenadaYInicial.getText());
            int CoorYFin = Integer.parseInt(jCoordenadaYFinal.getText());
            Calculo = Math.sqrt((CoorXFin - CoorXIni) * (CoorXFin - CoorXIni)) + Math.sqrt((CoorYFin - CoorYIni) * (CoorYFin - CoorYIni));
            jDistancia.setText(Calculo + "");
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "No pueden existir campos vacios para este calculo");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jCoordenadaXInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaXInicialKeyTyped
        if (jCoordenadaXInicial.getText().length() >= 3) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;

        if (!num) {
            evt.consume();
        }
    }//GEN-LAST:event_jCoordenadaXInicialKeyTyped

    private void jCoordenadaYInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaYInicialKeyTyped
        if (jCoordenadaYInicial.getText().length() >= 3) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;

        if (!num) {
            evt.consume();
        }
    }//GEN-LAST:event_jCoordenadaYInicialKeyTyped

    private void jCoordenadaXFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaXFinalKeyTyped
        if (jCoordenadaXFinal.getText().length() >= 3) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;

        if (!num) {
            evt.consume();
        }
    }//GEN-LAST:event_jCoordenadaXFinalKeyTyped

    private void jCoordenadaYFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaYFinalKeyTyped
        if (jCoordenadaYFinal.getText().length() >= 3) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;

        if (!num) {
            evt.consume();
        }
    }//GEN-LAST:event_jCoordenadaYFinalKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField jCoordenadaXFinal;
    private javax.swing.JTextField jCoordenadaXInicial;
    private javax.swing.JTextField jCoordenadaYFinal;
    private javax.swing.JTextField jCoordenadaYInicial;
    private javax.swing.JTextField jDistancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
  
    public void limpiar() {
        jCoordenadaXInicial.setText("");
        jCoordenadaXFinal.setText("");
        jCoordenadaYInicial.setText("");
        jCoordenadaYFinal.setText("");
        jDistancia.setText("");
    }
}
