/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberito.vistas;

import bomberito.accesoADatos.BrigadaData;
import bomberito.accesoADatos.CuartelData;
import bomberito.accesoADatos.SiniestroData;
import bomberito.entidades.Cuartel;
import bomberito.entidades.Siniestro;
import java.util.Map.Entry;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renat
 */


    /**
     * Creates new form CuartelMasCercano
     */

    
public class CuartelMasCercano extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };private DefaultTableModel modeloc = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
        SiniestroData controlSin=null;
    CuartelData controlCuar=null;
    BrigadaData controlBri=null;
    
    /**
     * Creates new form AsignarBrigadaASiniestro
     */
    public CuartelMasCercano() {
       initComponents();
        controlSin=new SiniestroData();
        controlCuar=new CuartelData();
        controlBri=new BrigadaData();
        modelo=new DefaultTableModel();
        modeloc=new DefaultTableModel();
        armarCabeceraTabla();
        cargarTabla();
        encabezadoTablaCuartel();
        cargarTablaCuartel();
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabladeSiniestro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCoordenadaX = new javax.swing.JTextField();
        jCoordenadaY = new javax.swing.JTextField();
        jTipoSiniestro = new javax.swing.JComboBox<>();
        jIdSiniestro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaCuartelesDistancia = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cuartel mas cercano al siniestro");

        jTabladeSiniestro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabladeSiniestro);

        jLabel2.setText("Id Siniestro");

        jLabel3.setText("Tipo");

        jLabel4.setText("Coordenadas ");

        jLabel5.setText("X");

        jLabel6.setText("Y");

        jCoordenadaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoordenadaXActionPerformed(evt);
            }
        });
        jCoordenadaX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCoordenadaXKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCoordenadaXKeyTyped(evt);
            }
        });

        jCoordenadaY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoordenadaYActionPerformed(evt);
            }
        });
        jCoordenadaY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCoordenadaYKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCoordenadaYKeyTyped(evt);
            }
        });

        jTipoSiniestro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Incendios en viviendas, e industrias ", "2- Salvamento en derrumbes", "3- Rescates en ámbito montaña ", "4- Rescate de personas atrapadas en accidentes de tráfico", "5- Socorrer inundaciones", "6- Operativos de prevención" }));
        jTipoSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoSiniestroActionPerformed(evt);
            }
        });
        jTipoSiniestro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTipoSiniestroKeyReleased(evt);
            }
        });

        jIdSiniestro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jIdSiniestroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIdSiniestroKeyTyped(evt);
            }
        });

        jTablaCuartelesDistancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaCuartelesDistancia);

        jLabel7.setText("Cuarteles por distancia :");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCoordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCoordenadaY, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(jIdSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTipoSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(282, 282, 282)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jIdSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTipoSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCoordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCoordenadaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCoordenadaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoordenadaXActionPerformed
        
    }//GEN-LAST:event_jCoordenadaXActionPerformed

    private void jCoordenadaYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoordenadaYActionPerformed
        
    }//GEN-LAST:event_jCoordenadaYActionPerformed

    private void jIdSiniestroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdSiniestroKeyTyped
  if (jIdSiniestro.getText().length() >= 11) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
        if (!num) {
            evt.consume();
        }       
    }//GEN-LAST:event_jIdSiniestroKeyTyped

    private void jIdSiniestroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdSiniestroKeyReleased
        borrarFilaTabla();
        for (Siniestro prod : controlSin.traerSiniestrosParaAsignar()) {
            String aux = prod.getIdSiniestro()+ "";
            if (aux.contains(jIdSiniestro.getText())) {
                modelo.addRow(new Object[]{
                prod.getIdSiniestro(),
                prod.getFechaSiniestro(),
                prod.getTipo(),
                prod.getCoordX(),
                prod.getCoordY(),
                prod.getDetalles(),
});
            }
        }

    }//GEN-LAST:event_jIdSiniestroKeyReleased

    private void jCoordenadaXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaXKeyReleased
                borrarFilaTabla();
        for (Siniestro prod : controlSin.traerSiniestrosParaAsignar()) {
            String aux = prod.getCoordX()+ "";
            if (aux.contains(jCoordenadaX.getText())) {
                modelo.addRow(new Object[]{
                prod.getIdSiniestro(),
                prod.getFechaSiniestro(),
                prod.getTipo(),
                prod.getCoordX(),
                prod.getCoordY(),
                prod.getDetalles(),
});
            }
        }
    }//GEN-LAST:event_jCoordenadaXKeyReleased

    private void jCoordenadaXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaXKeyTyped
      if (jCoordenadaX.getText().length() >= 3) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
        if (!num) {
            evt.consume();
        }  
    }//GEN-LAST:event_jCoordenadaXKeyTyped

    private void jCoordenadaYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaYKeyTyped
       if (jCoordenadaY.getText().length() >= 3) {
            evt.consume();
        }
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
        if (!num) {
            evt.consume();
        }   
    }//GEN-LAST:event_jCoordenadaYKeyTyped

    private void jCoordenadaYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoordenadaYKeyReleased
                       borrarFilaTabla();
        for (Siniestro prod : controlSin.traerSiniestrosParaAsignar()) {
            String aux = prod.getCoordY()+ "";
            if (aux.contains(jCoordenadaY.getText())) {
                modelo.addRow(new Object[]{
                prod.getIdSiniestro(),
                prod.getFechaSiniestro(),
                prod.getTipo(),
                prod.getCoordX(),
                prod.getCoordY(),
                prod.getDetalles(),
});
            }
        } 
    }//GEN-LAST:event_jCoordenadaYKeyReleased

    private void jTipoSiniestroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTipoSiniestroKeyReleased

    }//GEN-LAST:event_jTipoSiniestroKeyReleased

    private void jTipoSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoSiniestroActionPerformed
      borrarFilaTabla();
        for (Siniestro prod : controlSin.traerSiniestrosParaAsignar()) {
            String aux = prod.getTipo();
            String aux2= jTipoSiniestro.getSelectedItem()+"";
            if (aux.contains(aux2)) {;
                modelo.addRow(new Object[]{
                prod.getIdSiniestro(),
                prod.getFechaSiniestro(),
                prod.getTipo(),
                prod.getCoordX(),
                prod.getCoordY(),
                prod.getDetalles(),
});
            }
        }    
    }//GEN-LAST:event_jTipoSiniestroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
borrarFilaTabla2();
        int auxX = 0;
        int auxY = 0;
        double aux = 0;

        try{
            int auxXa = jTabladeSiniestro.getSelectedRow();
            
            auxX = (Integer) jTabladeSiniestro.getValueAt(auxXa, 3);
            auxY = (Integer) jTabladeSiniestro.getValueAt(auxXa, 4);
            jCoordenadaX.setText(auxX+"");
            jCoordenadaY.setText(auxY+"");
            int idsinselec= (Integer)jTabladeSiniestro.getValueAt(auxXa, 0);
            jIdSiniestro.setText(idsinselec+"");
            TreeMap<Integer, Cuartel> listaordenada = new TreeMap();

            for (Cuartel cuar : controlCuar.traerCuarteles()) {
                aux = Math.sqrt((cuar.getCoordX() - auxX) * (cuar.getCoordX() - auxX)) + Math.sqrt((cuar.getCoordY() - auxY) * (cuar.getCoordY() - auxY));
                int aux2 = (int) aux;
                listaordenada.put(aux2, cuar);
            }

            for (Entry<Integer, Cuartel> entry : listaordenada.entrySet()) {
                Integer key = entry.getKey();
                Cuartel value = entry.getValue();
                modeloc.addRow(new Object[]{
                    entry.getValue().getNombreCuartel(),
                    entry.getValue().getDireccion(),
                    entry.getValue().getTelefono(),
                    entry.getValue().getCorreo()
                });
            }
        }catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Error: Selecciona una fila válida en la tabla.","Error",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCoordenadaX;
    private javax.swing.JTextField jCoordenadaY;
    private javax.swing.JTextField jIdSiniestro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaCuartelesDistancia;
    private javax.swing.JTable jTabladeSiniestro;
    private javax.swing.JComboBox<String> jTipoSiniestro;
    // End of variables declaration//GEN-END:variables
 
    private void armarCabeceraTabla(){
      modelo.addColumn("ID");
      modelo.addColumn("Fecha");
      modelo.addColumn("Tipo");
      modelo.addColumn("X");
      modelo.addColumn("Y");
      modelo.addColumn("Detalles");
      jTabladeSiniestro.setModel(modelo);
      
      jTabladeSiniestro.setAutoResizeMode(jTabladeSiniestro.AUTO_RESIZE_OFF);
      jTabladeSiniestro.getColumnModel().getColumn(0).setPreferredWidth(17);
      jTabladeSiniestro.getColumnModel().getColumn(1).setPreferredWidth(67);
      jTabladeSiniestro.getColumnModel().getColumn(2).setPreferredWidth(330);
      jTabladeSiniestro.getColumnModel().getColumn(3).setPreferredWidth(25);
     jTabladeSiniestro.getColumnModel().getColumn(4).setPreferredWidth(25);
     jTabladeSiniestro.getColumnModel().getColumn(5).setPreferredWidth(320);

      
    }

    private void borrarFilaTabla(){
        int ind =modelo.getRowCount() -1;
            for(int i= ind;i>=0;i--){
                modelo.removeRow(i);
            }
                
    }
    private void borrarFilaTabla2(){
        int ind =modeloc.getRowCount() -1;
            for(int i= ind;i>=0;i--){
                modeloc.removeRow(i);
            }              
    }

    private void cargarTabla(){
        borrarFilaTabla();
        for(Siniestro cosa: controlSin.traerSiniestrosParaAsignar()){
            modelo.addRow(new Object[]{
                cosa.getIdSiniestro(),
                cosa.getFechaSiniestro(),
                cosa.getTipo(),
                cosa.getCoordX(),
                cosa.getCoordY(),
                cosa.getDetalles()
            });
        }
    }
       private void encabezadoTablaCuartel() {
        modeloc.addColumn("Nombre");
        modeloc.addColumn("Dirección");
        modeloc.addColumn("Teléfono");
       modeloc.addColumn("Correo");
       jTablaCuartelesDistancia.setModel(modeloc);
    }

    private void cargarTablaCuartel() {
        for (Cuartel cuar : controlCuar.traerCuarteles()) {
            modeloc.addRow(new Object[]{
                cuar.getNombreCuartel(),
                cuar.getDireccion(),
                cuar.getTelefono(),
                cuar.getCorreo()});
        }
    }
}
