/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberito.vistas;

import bomberito.accesoADatos.BrigadaData;
import bomberito.accesoADatos.SiniestroData;
import bomberito.entidades.Siniestro;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melina
 */
public class ResolucionDeSiniestro extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    SiniestroData controlSin=null;
    BrigadaData controlBri=null;
    /**
     * Creates new form ResolucionDeSiniestro
     */
    public ResolucionDeSiniestro() {
        initComponents();
        modelo=new DefaultTableModel();
        controlSin=new SiniestroData();
        controlBri=new BrigadaData();
        armarCabeceraTabla();
        cargarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        FechaRes = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        CBPunt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Resolucion de Siniestro");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Siniestros");

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTabla);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Fecha de Resolucion:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Puntuacion:");

        CBPunt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2)))
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaRes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(FechaRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(CBPunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        Date fRes=FechaRes.getDate();
        LocalDate FechaResolucion= fRes.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String punts=CBPunt.getSelectedItem().toString();
        int puntuacion=Integer.parseInt(punts);
        boolean activo=false;
        int sinSelec = JTabla.getSelectedRow();
        int idSiniestro = (Integer)JTabla.getValueAt(sinSelec,0);
        
        controlSin.actSiniestrosRes(FechaResolucion, puntuacion, activo, idSiniestro);
        int idSelec=JTabla.getSelectedRow();
        String brigadaString=(String)JTabla.getValueAt(idSelec, 3);
        int inicio=brigadaString.indexOf('[');
        int fin=brigadaString.indexOf(']');
        if (inicio !=-1 && fin !=-1 && inicio<fin){
            String numBrigada= brigadaString.substring(inicio+1,fin);
            int idBrigada= Integer.parseInt(numBrigada);
            boolean libre=true;
        controlSin.actualizarBrigada(idBrigada, libre);
        }
        actualizarTabla();
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos, intente nuevamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPunt;
    private com.toedter.calendar.JDateChooser FechaRes;
    private javax.swing.JTable JTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    private void armarCabeceraTabla(){
      modelo.addColumn("ID");
      modelo.addColumn("Fecha");
      modelo.addColumn("Tipo");
      modelo.addColumn("Brigada");
      modelo.addColumn("Detalles");
      JTabla.setModel(modelo);
      
      JTabla.setAutoResizeMode(JTabla.AUTO_RESIZE_OFF);
      JTabla.getColumnModel().getColumn(0).setPreferredWidth(17);
      JTabla.getColumnModel().getColumn(1).setPreferredWidth(67);
      JTabla.getColumnModel().getColumn(2).setPreferredWidth(330);
      JTabla.getColumnModel().getColumn(3).setPreferredWidth(70);
      JTabla.getColumnModel().getColumn(4).setPreferredWidth(300);

      
    }


    private void cargarTabla() {
        for (Siniestro cosa : controlSin.traerResDeSiniestro()) {
            String briNombreID = "[" + cosa.getCodBrigada().getIdBrigada() + "] " + cosa.getCodBrigada().getNombreBrigada();
            modelo.addRow(new Object[]{
                cosa.getIdSiniestro(),
                cosa.getFechaSiniestro(),
                cosa.getTipo(),
                briNombreID, //Nombre e identificador de la brigada   cosa.getCodBrigada().getNombreBrigada(), <--- Solo sale el numero, solo puedo mostrar una cosa a la vez 
                cosa.getDetalles()
            });
        }
    }

    private void actualizarTabla() {
        modelo.setRowCount(0);
        cargarTabla();
    }
}
